services:
  kind-robots:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/silasfelinus/cosmos
    container_name: cosmos
    ports:
      - "3019:3000"
    expose:
      - 3000
    volumes:
      - /mnt/europa/appdata/cosmos:/
    restart: unless-stopped
    environment:

    labels:
      -  "traefik.enable: true"
      -  "traefik.http.routers.cosmos.entryPoints: https"
    networks:
      - cafepurr
networks:
  cafepurr:
    external: true
    name: cafepurr