name: Deploy Cosmos

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Build Docker image and push
      run: |
        docker build -t username/cosmos:${{ github.sha }} .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push username/cosmos:${{ github.sha }}

    - name: Deploy Docker image
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_HOST }} "docker pull username/cosmos:${{ github.sha }} && docker run -d --name cosmos -p 3000:3000 username/cosmos:${{ github.sha }}"
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
